export interface Movie {
 id?: number; // Optional because it will be auto-generated by the database
 year: number;
 title: string;
 studios: string;
 producers: string;
 winner: boolean; // Use boolean in TypeScript, convert to INTEGER in SQLite
}
